[package]
name = "words_counter"
version = "1.0.0"
authors = ["pipopotamasu <ec0156hx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "=3.0.0-beta.2"
